#!/usr/bin/env sh
set -e

# Change to inception-angular directory
cd "$(git rev-parse --show-toplevel)/src/inception-angular"

# Run lint
#yarn lint-staged

# Run the security audit
node pre-commit-audit.js
