DELETE FROM DATABASECHANGELOG;
DELETE FROM DATABASECHANGELOGLOCK;

DROP TABLE IDGENERATOR;

DROP TABLE CODES;
DROP TABLE CODE_CATEGORIES;
DROP TABLE CONFIG;

DROP TABLE ERROR_REPORTS;

DROP TABLE JOB_PARAMETERS;
DROP TABLE JOBS;

DROP TABLE MAIL_TEMPLATES;

DROP TABLE REPORT_DEFINITIONS;

DROP TABLE PASSWORD_RESETS;
DROP TABLE ROLE_TO_GROUP_MAP;
DROP TABLE FUNCTION_TO_ROLE_MAP;
DROP TABLE ROLES;
DROP TABLE FUNCTIONS;
DROP TABLE USER_TO_GROUP_MAP;
DROP TABLE GROUPS;
DROP TABLE USERS_PASSWORD_HISTORY;
DROP TABLE USERS;
DROP TABLE USER_DIRECTORY_TO_TENANT_MAP;
DROP TABLE USER_DIRECTORIES;
DROP TABLE USER_DIRECTORY_TYPES;
DROP TABLE TENANTS;

DROP TABLE REGIONS;
DROP TABLE MEASUREMENT_UNITS;
DROP TABLE MEASUREMENT_UNIT_TYPES;
DROP TABLE MEASUREMENT_SYSTEMS;
DROP TABLE LANGUAGES;
DROP TABLE COUNTRIES;

DROP TABLE DATA;
DROP TABLE VEHICLE_ATTRIBUTES;
DROP TABLE VEHICLE_ATTRIBUTE_TYPES;
DROP TABLE CARS;
DROP TABLE VEHICLES;



