package digital.inception.codes.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-02-12T07:54:14.255+02:00
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "CodesService",
                  wsdlLocation = "file:/Users/marcus/Develop/MMP/inception/src/inception-demo-client/src/main/resources/META-INF/wsdl/CodesService.wsdl",
                  targetNamespace = "http://inception.digital/codes")
public class CodesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inception.digital/codes", "CodesService");
    public final static QName ICodesServicePort = new QName("http://inception.digital/codes", "ICodesServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/marcus/Develop/MMP/inception/src/inception-demo-client/src/main/resources/META-INF/wsdl/CodesService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CodesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/marcus/Develop/MMP/inception/src/inception-demo-client/src/main/resources/META-INF/wsdl/CodesService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CodesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CodesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CodesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CodesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CodesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CodesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICodesService
     */
    @WebEndpoint(name = "ICodesServicePort")
    public ICodesService getICodesServicePort() {
        return super.getPort(ICodesServicePort, ICodesService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICodesService
     */
    @WebEndpoint(name = "ICodesServicePort")
    public ICodesService getICodesServicePort(WebServiceFeature... features) {
        return super.getPort(ICodesServicePort, ICodesService.class, features);
    }

}
