
package digital.inception.codes.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-02-12T07:54:14.246+02:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "CodeNotFoundException", targetNamespace = "http://inception.digital/codes")
public class CodeNotFoundException extends Exception {

    private digital.inception.core.ws.client.ServiceError faultInfo;

    public CodeNotFoundException() {
        super();
    }

    public CodeNotFoundException(String message) {
        super(message);
    }

    public CodeNotFoundException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CodeNotFoundException(String message, digital.inception.core.ws.client.ServiceError codeNotFoundException) {
        super(message);
        this.faultInfo = codeNotFoundException;
    }

    public CodeNotFoundException(String message, digital.inception.core.ws.client.ServiceError codeNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = codeNotFoundException;
    }

    public digital.inception.core.ws.client.ServiceError getFaultInfo() {
        return this.faultInfo;
    }
}
