
package digital.inception.codes.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-02-12T07:54:14.241+02:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "DuplicateCodeException", targetNamespace = "http://inception.digital/codes")
public class DuplicateCodeException extends Exception {

    private digital.inception.core.ws.client.ServiceError faultInfo;

    public DuplicateCodeException() {
        super();
    }

    public DuplicateCodeException(String message) {
        super(message);
    }

    public DuplicateCodeException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DuplicateCodeException(String message, digital.inception.core.ws.client.ServiceError duplicateCodeException) {
        super(message);
        this.faultInfo = duplicateCodeException;
    }

    public DuplicateCodeException(String message, digital.inception.core.ws.client.ServiceError duplicateCodeException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = duplicateCodeException;
    }

    public digital.inception.core.ws.client.ServiceError getFaultInfo() {
        return this.faultInfo;
    }
}
