
package digital.inception.codes.ws.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-02-12T10:46:22.707+02:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "DuplicateCodeCategoryException", targetNamespace = "https://inception.digital/codes")
public class DuplicateCodeCategoryException extends Exception {

    private digital.inception.core.ws.client.ServiceError faultInfo;

    public DuplicateCodeCategoryException() {
        super();
    }

    public DuplicateCodeCategoryException(String message) {
        super(message);
    }

    public DuplicateCodeCategoryException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DuplicateCodeCategoryException(String message, digital.inception.core.ws.client.ServiceError duplicateCodeCategoryException) {
        super(message);
        this.faultInfo = duplicateCodeCategoryException;
    }

    public DuplicateCodeCategoryException(String message, digital.inception.core.ws.client.ServiceError duplicateCodeCategoryException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = duplicateCodeCategoryException;
    }

    public digital.inception.core.ws.client.ServiceError getFaultInfo() {
        return this.faultInfo;
    }
}
