package digital.inception.codes.ws.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-02-12T07:54:14.248+02:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://inception.digital/codes", name = "ICodesService")
@XmlSeeAlso({digital.inception.core.ws.client.ObjectFactory.class, ObjectFactory.class})
public interface ICodesService {

    @WebMethod(operationName = "CreateCode")
    @RequestWrapper(localName = "CreateCode", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.CreateCode")
    @ResponseWrapper(localName = "CreateCodeResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.CreateCodeResponse")
    public void createCode(

        @WebParam(name = "Code", targetNamespace = "")
        digital.inception.codes.ws.client.Code code
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException, DuplicateCodeException;

    @WebMethod(operationName = "CreateCodeCategory")
    @RequestWrapper(localName = "CreateCodeCategory", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.CreateCodeCategory")
    @ResponseWrapper(localName = "CreateCodeCategoryResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.CreateCodeCategoryResponse")
    public void createCodeCategory(

        @WebParam(name = "CodeCategory", targetNamespace = "")
        digital.inception.codes.ws.client.CodeCategory codeCategory
    ) throws InvalidArgumentException, ServiceUnavailableException, DuplicateCodeCategoryException;

    @WebMethod(operationName = "DeleteCode")
    @RequestWrapper(localName = "DeleteCode", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.DeleteCode")
    @ResponseWrapper(localName = "DeleteCodeResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.DeleteCodeResponse")
    public void deleteCode(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId,
        @WebParam(name = "CodeId", targetNamespace = "")
        java.lang.String codeId
    ) throws InvalidArgumentException, ServiceUnavailableException, CodeNotFoundException;

    @WebMethod(operationName = "GetCodeCategory")
    @RequestWrapper(localName = "GetCodeCategory", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategory")
    @ResponseWrapper(localName = "GetCodeCategoryResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryResponse")
    @WebResult(name = "CodeCategory", targetNamespace = "")
    public digital.inception.codes.ws.client.CodeCategory getCodeCategory(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "GetCodes")
    @RequestWrapper(localName = "GetCodes", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodes")
    @ResponseWrapper(localName = "GetCodesResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodesResponse")
    @WebResult(name = "Code", targetNamespace = "")
    public java.util.List<digital.inception.codes.ws.client.Code> getCodes(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "GetCodeCategorySummaries")
    @RequestWrapper(localName = "GetCodeCategorySummaries", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategorySummaries")
    @ResponseWrapper(localName = "GetCodeCategorySummariesResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategorySummariesResponse")
    @WebResult(name = "CodeCategorySummary", targetNamespace = "")
    public java.util.List<digital.inception.codes.ws.client.CodeCategorySummary> getCodeCategorySummaries()
 throws ServiceUnavailableException;

    @WebMethod(operationName = "GetCodeName")
    @RequestWrapper(localName = "GetCodeName", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeName")
    @ResponseWrapper(localName = "GetCodeNameResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeNameResponse")
    @WebResult(name = "CodeName", targetNamespace = "")
    public java.lang.String getCodeName(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId,
        @WebParam(name = "CodeId", targetNamespace = "")
        java.lang.String codeId
    ) throws InvalidArgumentException, ServiceUnavailableException, CodeNotFoundException;

    @WebMethod(operationName = "GetCodeCategories")
    @RequestWrapper(localName = "GetCodeCategories", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategories")
    @ResponseWrapper(localName = "GetCodeCategoriesResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoriesResponse")
    @WebResult(name = "CodeCategory", targetNamespace = "")
    public java.util.List<digital.inception.codes.ws.client.CodeCategory> getCodeCategories()
 throws ServiceUnavailableException;

    @WebMethod(operationName = "GetCode")
    @RequestWrapper(localName = "GetCode", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCode")
    @ResponseWrapper(localName = "GetCodeResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeResponse")
    @WebResult(name = "Code", targetNamespace = "")
    public digital.inception.codes.ws.client.Code getCode(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId,
        @WebParam(name = "CodeId", targetNamespace = "")
        java.lang.String codeId
    ) throws InvalidArgumentException, ServiceUnavailableException, CodeNotFoundException;

    @WebMethod(operationName = "GetCodeCategoryData")
    @RequestWrapper(localName = "GetCodeCategoryData", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryData")
    @ResponseWrapper(localName = "GetCodeCategoryDataResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryDataResponse")
    @WebResult(name = "CodeCategoryData", targetNamespace = "")
    public java.lang.String getCodeCategoryData(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "DeleteCodeCategory")
    @RequestWrapper(localName = "DeleteCodeCategory", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.DeleteCodeCategory")
    @ResponseWrapper(localName = "DeleteCodeCategoryResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.DeleteCodeCategoryResponse")
    public void deleteCodeCategory(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "GetCodeCategoryName")
    @RequestWrapper(localName = "GetCodeCategoryName", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryName")
    @ResponseWrapper(localName = "GetCodeCategoryNameResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryNameResponse")
    @WebResult(name = "GetCodeCategoryName", targetNamespace = "")
    public java.lang.String getCodeCategoryName(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "UpdateCode")
    @RequestWrapper(localName = "UpdateCode", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.UpdateCode")
    @ResponseWrapper(localName = "UpdateCodeResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.UpdateCodeResponse")
    public void updateCode(

        @WebParam(name = "Code", targetNamespace = "")
        digital.inception.codes.ws.client.Code code
    ) throws InvalidArgumentException, ServiceUnavailableException, CodeNotFoundException;

    @WebMethod(operationName = "UpdateCodeCategory")
    @RequestWrapper(localName = "UpdateCodeCategory", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.UpdateCodeCategory")
    @ResponseWrapper(localName = "UpdateCodeCategoryResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.UpdateCodeCategoryResponse")
    public void updateCodeCategory(

        @WebParam(name = "CodeCategory", targetNamespace = "")
        digital.inception.codes.ws.client.CodeCategory codeCategory
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;

    @WebMethod(operationName = "GetCodeCategoryLastModified")
    @RequestWrapper(localName = "GetCodeCategoryLastModified", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryLastModified")
    @ResponseWrapper(localName = "GetCodeCategoryLastModifiedResponse", targetNamespace = "http://inception.digital/codes", className = "digital.inception.codes.ws.client.GetCodeCategoryLastModifiedResponse")
    @WebResult(name = "CodeCategoryLastModified", targetNamespace = "")
    public java.time.OffsetDateTime getCodeCategoryLastModified(

        @WebParam(name = "CodeCategoryId", targetNamespace = "")
        java.lang.String codeCategoryId
    ) throws InvalidArgumentException, CodeCategoryNotFoundException, ServiceUnavailableException;
}
