package digital.inception.codes.ws.client;

import jakarta.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 4.0.2 2025-02-12T10:46:22.678+02:00 Generated source
 * version: 4.0.2
 */
@WebFault(name = "ServiceUnavailableException", targetNamespace = "https://inception.digital/core")
public class ServiceUnavailableException extends Exception {

  private digital.inception.core.ws.client.ServiceError faultInfo;

  public ServiceUnavailableException() {
    super();
  }

  public ServiceUnavailableException(String message) {
    super(message);
  }

  public ServiceUnavailableException(String message, java.lang.Throwable cause) {
    super(message, cause);
  }

  public ServiceUnavailableException(
      String message, digital.inception.core.ws.client.ServiceError serviceUnavailableException) {
    super(message);
    this.faultInfo = serviceUnavailableException;
  }

  public ServiceUnavailableException(
      String message,
      digital.inception.core.ws.client.ServiceError serviceUnavailableException,
      java.lang.Throwable cause) {
    super(message, cause);
    this.faultInfo = serviceUnavailableException;
  }

  public digital.inception.core.ws.client.ServiceError getFaultInfo() {
    return this.faultInfo;
  }
}
