/*
 * Copyright 2021 Marcus Portmann
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package digital.inception.api;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.springframework.http.HttpStatus;

/**
 * The <b>Problem</b> annotation is applied to an exception thrown by an API to specify how the
 * exception should be returned as a RFC 7807 JSON Problem Details Object.
 *
 * @author Marcus Portmann
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Problem {
  /** The HTTP status code generated by the origin server for an occurrence of the problem. */
  HttpStatus status() default HttpStatus.INTERNAL_SERVER_ERROR;

  /** The short, human-readable summary of the problem type. */
  String title();

  /** The URI reference that identifies the problem type. */
  String type() default "about:blank";
}
