-- -------------------------------------------------------------------------------------------------
-- CREATE SCHEMAS
-- -------------------------------------------------------------------------------------------------
CREATE SCHEMA reporting;

-- -- -------------------------------------------------------------------------------------------------
-- -- CREATE SEQUENCES
-- -- -------------------------------------------------------------------------------------------------
-- CREATE SEQUENCE reporting.report_definition_id_seq START WITH 1000000 INCREMENT BY 1;

-- -------------------------------------------------------------------------------------------------
-- CREATE TABLES
-- -------------------------------------------------------------------------------------------------
CREATE TABLE reporting.report_definitions (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000 INCREMENT BY 1),
  name     VARCHAR(100) NOT NULL,
  template BLOB         NOT NULL,

  PRIMARY KEY (id)
);

COMMENT ON COLUMN reporting.report_definitions.id IS 'The ID used to uniquely identify the report definition';

COMMENT ON COLUMN reporting.report_definitions.name IS 'The name of the report definition';

COMMENT ON COLUMN reporting.report_definitions.template IS 'The JasperReports template for the report definition';

-- -------------------------------------------------------------------------------------------------
-- POPULATE TABLES
-- -------------------------------------------------------------------------------------------------

