/*
 * Copyright Marcus Portmann
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package digital.inception.core.reference;

import java.util.List;
import java.util.Optional;

/**
 * The {@code Countries} class provides static reference data for countries.
 *
 * @author Marcus Portmann
 */
public final class Countries {

  /** The list of countries. */
  private static final List<Country> countries =
      List.of(
          new Country("ZZ", "ZZZ", 0, "Unknown", "Unknown", "Unknown", "ZA", "Unknown"),
          new Country("AF", "AFG", 1, "Afghanistan", "Afghanistan", "Afghanistan", "AF", "Afghan"),
          new Country(
              "AL",
              "ALB",
              1,
              "Republic of Albania",
              "Albania",
              "Republic of Albania",
              "AL",
              "Albanian"),
          new Country(
              "DZ",
              "DZA",
              1,
              "People's Democratic Republic of Algeria",
              "Algeria",
              "People's Democratic Republic of Algeria",
              "DZ",
              "Algerian"),
          new Country(
              "AS", "ASM", 1, "American Samoa", "American Samoa", "American Samoa", "US", "Samoan"),
          new Country(
              "AD",
              "AND",
              1,
              "Principality of Andorra",
              "Andorra",
              "Principality of Andorra",
              "AD",
              "Andorran"),
          new Country(
              "AO",
              "AGO",
              1,
              "Republic of Angola",
              "Angola",
              "Republic of Angola",
              "AO",
              "Angolan"),
          new Country("AI", "AIA", 1, "Anguilla", "Anguilla", "Anguilla", "GB", "Anguillan"),
          new Country("AQ", "ATA", 1, "Antarctica", "Antarctica", "Antarctica", "AQ", "Antarctic"),
          new Country(
              "AG",
              "ATG",
              1,
              "Antigua and Barbuda",
              "Antigua and Barbuda",
              "Antigua and Barbuda",
              "AG",
              "Antiguan"),
          new Country(
              "AR",
              "ARG",
              1,
              "Argentine Republic",
              "Argentina",
              "Argentine Republic",
              "AR",
              "Argentine"),
          new Country(
              "AM",
              "ARM",
              1,
              "Republic of Armenia",
              "Armenia",
              "Republic of Armenia",
              "AM",
              "Armenian"),
          new Country("AW", "ABW", 1, "Aruba", "Aruba", "Aruba", "NL", "Arubian"),
          new Country(
              "AU",
              "AUS",
              1,
              "Commonwealth of Australia",
              "Australia",
              "Commonwealth of Australia",
              "AU",
              "Australian"),
          new Country(
              "AT",
              "AUT",
              1,
              "Republic of Austria",
              "Austria",
              "Republic of Austria",
              "AT",
              "Austrian"),
          new Country(
              "AZ",
              "AZE",
              1,
              "Republic of Azerbaijan",
              "Azerbaijan",
              "Republic of Azerbaijan",
              "AZ",
              "Azerbaijani"),
          new Country(
              "BH",
              "BHR",
              1,
              "Kingdom of Bahrain",
              "Bahrain",
              "Kingdom of Bahrain",
              "BH",
              "Bahrainian"),
          new Country(
              "BD",
              "BGD",
              1,
              "People's Republic of Bangladesh",
              "Bangladesh",
              "People's Republic of Bangladesh",
              "BD",
              "Bangladeshi"),
          new Country("BB", "BRB", 1, "Barbados", "Barbados", "Barbados", "BB", "Barbadian"),
          new Country(
              "BY",
              "BLR",
              1,
              " Republic of Belarus",
              "Belarus",
              " Republic of Belarus",
              "BY",
              "Belarusian"),
          new Country(
              "BE",
              "BEL",
              1,
              "Kingdom of Belgium",
              "Belgium",
              "Kingdom of Belgium",
              "BE",
              "Belgian"),
          new Country("BZ", "BLZ", 1, "Belize", "Belize", "Belize", "BZ", "Belizean"),
          new Country(
              "BJ", "BEN", 1, "Republic of Benin", "Benin", "Republic of Benin", "BJ", "Beninese"),
          new Country("BM", "BMU", 1, "Bermuda", "Bermuda", "Bermuda", "GB", "Bermudan"),
          new Country(
              "BT",
              "BTN",
              1,
              "Kingdom of Bhutan",
              "Bhutan",
              "Kingdom of Bhutan",
              "BT",
              "Bhutanese"),
          new Country(
              "BO",
              "BOL",
              1,
              "Plurinational State of Bolivia",
              "Bolivia",
              "Plurinational State of Bolivia",
              "BO",
              "Bolivian"),
          new Country(
              "BA",
              "BIH",
              1,
              "Bosnia and Herzegovina",
              "Bosnia and Herzegovina",
              "Bosnia and Herzegovina",
              "BA",
              "Bosnian and Herzegovinian"),
          new Country("BW", "BWA", 1, "Botswana", "Botswana", "Botswana", "BW", "Motswana"),
          new Country(
              "BV", "BVT", 1, "Bouvet Island", "Bouvet Island", "Bouvet Island", "NO", "Norwegian"),
          new Country("BR", "BRA", 1, "Brazil", "Brazil", "Brazil", "BR", "Brazilian"),
          new Country(
              "VG",
              "VGB",
              1,
              "Virgin Islands",
              "British Virgin Islands",
              "Virgin Islands",
              "GB",
              "Virgin Islander"),
          new Country(
              "BN", "BRN", 1, "Nation of Brunei", "Brunei", "Nation of Brunei", "BN", "Bruneian"),
          new Country(
              "BG",
              "BGR",
              1,
              "Republic of Bulgaria",
              "Bulgaria",
              "Republic of Bulgaria",
              "BG",
              "Bulgarian"),
          new Country(
              "BF", "BFA", 1, "Burkina Faso", "Burkina Faso", "Burkina Faso", "BF", "Burkinabe"),
          new Country(
              "BI",
              "BDI",
              1,
              "Republic of Burundi",
              "Burundi",
              "Republic of Burundi",
              "BI",
              "Burundian"),
          new Country(
              "KH",
              "KHM",
              1,
              "Kingdom of Cambodia",
              "Cambodia",
              "Kingdom of Cambodia",
              "KH",
              "Cambodian"),
          new Country("CM", "CMR", 1, "Cameroon", "Cameroon", "Cameroon", "CM", "Cameroonian"),
          new Country("CA", "CAN", 1, "Canada", "Canada", "Canada", "CA", "Canadian"),
          new Country(
              "BQ",
              "BES",
              1,
              "Bonaire, Sint Eustatius and Saba",
              "Caribbean Netherlands",
              "Bonaire, Sint Eustatius and Saba (Caribbean Netherlands)",
              "NL",
              "Dutch"),
          new Country(
              "KY",
              "CYM",
              1,
              "Cayman Islands",
              "Cayman Islands",
              "Cayman Islands",
              "GB",
              "Caymanian"),
          new Country(
              "CF",
              "CAF",
              1,
              "Central African Republic",
              "Central African Republic",
              "Central African Republic",
              "CF",
              "Central African"),
          new Country(
              "TD", "TCD", 1, "Republic of Chad", "Chad", "Republic of Chad", "TD", "Chadian"),
          new Country(
              "CL", "CHL", 1, "Republic of Chile", "Chile", "Republic of Chile", "CL", "Chilean"),
          new Country("CN", "CHN", 1, "China", "China", "China", "CN", "Chinese"),
          new Country(
              "CX",
              "CXR",
              1,
              "Christmas Island",
              "Christmas Island",
              "Christmas Island",
              "AU",
              "Christmas Islander"),
          new Country(
              "CC",
              "CCK",
              1,
              "Cocos (Keeling) Islands",
              "Cocos (Keeling) Islands",
              "Cocos (Keeling) Islands",
              "AU",
              "Cocos Islandia"),
          new Country(
              "CO",
              "COL",
              1,
              "Republic of Colombia",
              "Colombia",
              "Republic of Colombia",
              "CO",
              "Colombian"),
          new Country(
              "KM",
              "COM",
              1,
              "Union of the Comoros",
              "Comoros",
              "Union of the Comoros",
              "KM",
              "Comoran"),
          new Country(
              "CG", "COG", 1, "Republic of Congo", "Congo", "Republic of Congo", "CG", "Congolese"),
          new Country(
              "CK",
              "COK",
              1,
              "Cook Islands",
              "Cook Islands",
              "Cook Islands",
              "CK",
              "Cook Islander"),
          new Country(
              "CR",
              "CRI",
              1,
              "Republic of Costa Rica",
              "Costa Rica",
              "Republic of Costa Rica",
              "CR",
              "Costa Rican"),
          new Country(
              "HR",
              "HRV",
              1,
              "Republic of Croatia",
              "Croatia",
              "Republic of Croatia",
              "HR",
              "Croatian"),
          new Country(
              "CU", "CUB", 1, "Republic of Cuba", "Cuba", "Republic of Cuba", "CU", "Cuban"),
          new Country("CW", "CUW", 1, "Curaçao", "Curaçao", "Curaçao", "NL", "Curaçaoan"),
          new Country(
              "CY",
              "CYP",
              1,
              "Republic of Cyprus",
              "Cyprus",
              "Republic of Cyprus",
              "CY",
              "Cypriot"),
          new Country(
              "CZ",
              "CZE",
              1,
              "Czech Republic",
              "Czech Republic",
              "Czechia, Czech Republic",
              "CZ",
              "Czech"),
          new Country(
              "CI",
              "CIV",
              1,
              "Republic of Côte d'Ivoire",
              "Côte d'Ivoire",
              "Côte d'Ivoire (Ivory Coast)",
              "CI",
              "Ivorian"),
          new Country(
              "CD",
              "COD",
              1,
              "Democratic Republic of the Congo",
              "Dem. Rep. of the Congo",
              "Democratic Republic of the Congo",
              "CD",
              "Congolese"),
          new Country(
              "DK",
              "DNK",
              1,
              "Kingdom of Denmark",
              "Denmark",
              "Kingdom of Denmark",
              "DK",
              "Danish"),
          new Country(
              "DJ",
              "DJI",
              1,
              "Republic of Djibouti",
              "Djibouti",
              "Republic of Djibouti",
              "DJ",
              "Djiboutian"),
          new Country(
              "DM",
              "DMA",
              1,
              " Commonwealth of Dominica",
              "Dominica",
              " Commonwealth of Dominica",
              "DM",
              "Dominican"),
          new Country(
              "DO",
              "DOM",
              1,
              "Dominican Republic",
              "Dominican Republic",
              "Dominican Republic",
              "DO",
              "Dominican"),
          new Country(
              "TL",
              "TLS",
              1,
              "Democratic Republic of Timor-Leste",
              "East Timor",
              "Democratic Republic of Timor-Leste",
              "TL",
              "Timorese"),
          new Country(
              "EC",
              "ECU",
              1,
              "Republic of Ecuador",
              "Ecuador",
              "Republic of Ecuador",
              "EC",
              "Ecuadorian"),
          new Country(
              "EG",
              "EGY",
              1,
              "Arab Republic of Egypt",
              "Egypt",
              "Arab Republic of Egypt",
              "EG",
              "Egyptian"),
          new Country(
              "SV",
              "SLV",
              1,
              "Republic of El Salvador",
              "El Salvador",
              "Republic of El Salvador",
              "SV",
              "Salvadoran"),
          new Country(
              "GQ",
              "GNQ",
              1,
              "Republic of Equatorial Guinea",
              "Equatorial Guinea",
              "Republic of Equatorial Guinea",
              "GQ",
              "Equatoguinean"),
          new Country(
              "ER", "ERI", 1, "State of Eritrea", "Eritrea", "State of Eritrea", "ER", "Eritrean"),
          new Country(
              "EE",
              "EST",
              1,
              "Republic of Estonia",
              "Estonia",
              "Republic of Estonia",
              "EE",
              "Estonian"),
          new Country(
              "ET",
              "ETH",
              1,
              "Federal Democratic Republic of Ethiopia",
              "Ethiopia",
              "Federal Democratic Republic of Ethiopia",
              "ET",
              "Ethiopian"),
          new Country(
              "FK",
              "FLK",
              1,
              "Falkland Islands (Malvinas)",
              "Falkland Islands",
              "Falkland Islands (Malvinas)",
              "GB",
              "Falkland Islander"),
          new Country(
              "FO", "FRO", 1, "Faroe Islands", "Faroe Islands", "Faroe Islands", "DK", "Faroese"),
          new Country(
              "FJ", "FJI", 1, "Republic of Fiji", "Fiji", "Republic of Fiji", "FJ", "Fijian"),
          new Country(
              "FI",
              "FIN",
              1,
              "Republic of Finland",
              "Finland",
              "Republic of Finland",
              "FI",
              "Finnish"),
          new Country(
              "FR", "FRA", 1, "French Republic", "France", "French Republic", "FR", "French"),
          new Country(
              "GF",
              "GUF",
              1,
              "French Guiana",
              "French Guiana",
              "French Guiana",
              "FR",
              "French Guianese"),
          new Country(
              "PF",
              "PYF",
              1,
              "Collectivity of French Polynesia",
              "French Polynesia",
              "Collectivity of French Polynesia",
              "FR",
              "French Polynesian"),
          new Country(
              "TF",
              "ATF",
              1,
              "French Southern and Antarctic Lands",
              "French Southern Territories",
              "French Southern and Antarctic Lands",
              "FR",
              "French"),
          new Country(
              "GA", "GAB", 1, "Gabonese Republic", "Gabon", "Gabonese Republic", "GA", "Gabonese"),
          new Country(
              "GM",
              "GMB",
              1,
              "Republic of The Gambia",
              "Gambia",
              "Republic of The Gambia",
              "GM",
              "Gambian"),
          new Country("GE", "GEO", 1, "Georgia", "Georgia", "Georgia", "GE", "Georgian"),
          new Country(
              "DE",
              "DEU",
              1,
              "Federal Republic of Germany",
              "Germany",
              "Federal Republic of Germany",
              "DE",
              "German"),
          new Country(
              "GH", "GHA", 1, "Republic of Ghana", "Ghana", "Republic of Ghana", "GH", "Ghanaian"),
          new Country("GI", "GIB", 1, "Gibraltar", "Gibraltar", "Gibraltar", "GB", "Gibraltarian"),
          new Country(
              "GR", "GRC", 1, "Hellenic Republic", "Greece", "Hellenic Republic", "GR", "Greek"),
          new Country("GL", "GRL", 1, "Greenland", "Greenland", "Greenland", "GL", "Greenlandic"),
          new Country("GD", "GRD", 1, "Grenada", "Grenada", "Grenada", "GD", "Grenadian"),
          new Country(
              "GP", "GLP", 1, "Guadeloupe", "Guadeloupe", "Guadeloupe", "FR", "Guadeloupean"),
          new Country("GU", "GUM", 1, "Guam", "Guam", "Guam", "US", "Guamanian"),
          new Country(
              "GT",
              "GTM",
              1,
              "Republic of Guatemala",
              "Guatemala",
              "Republic of Guatemala",
              "GT",
              "Guatemalan"),
          new Country("GG", "GGY", 1, "Guernsey", "Guernsey", "Guernsey", "GB", "British"),
          new Country(
              "GN",
              "GIN",
              1,
              "Republic of Guinea",
              "Guinea",
              "Republic of Guinea",
              "GN",
              "Guinean"),
          new Country(
              "GW",
              "GNB",
              1,
              "Republic of Guinea-Bissau",
              "Guinea-Bissau",
              "Republic of Guinea-Bissau",
              "GW",
              "Guinean"),
          new Country(
              "GY",
              "GUY",
              1,
              "Co-operative Republic of Guyana",
              "Guyana",
              "Co-operative Republic of Guyana",
              "GY",
              "Guyanese"),
          new Country(
              "HT", "HTI", 1, "Republic of Haiti", "Haiti", "Republic of Haiti", "HT", "Haitian"),
          new Country("VA", "VAT", 1, "Holy See", "Holy See", "Holy See", "VA", "Papal"),
          new Country(
              "HN",
              "HND",
              1,
              "Republic of Honduras",
              "Honduras",
              "Republic of Honduras",
              "HN",
              "Honduran"),
          new Country(
              "HK",
              "HKG",
              1,
              "Hong Kong",
              "Hong Kong",
              "Hong Kong Special Administrative Region of the People's Republic of China",
              "CN",
              "Hong Konger"),
          new Country("HU", "HUN", 1, "Hungary", "Hungary", "Hungary", "HU", "Hungarian"),
          new Country("IS", "ISL", 1, "Iceland", "Iceland", "Iceland", "IS", "Icelander"),
          new Country(
              "IN", "IND", 1, "Republic of India", "India", "Republic of India", "IN", "Indian"),
          new Country(
              "ID",
              "IDN",
              1,
              "Republic of Indonesia",
              "Indonesia",
              "Republic of Indonesia",
              "ID",
              "Indonesian"),
          new Country(
              "IR",
              "IRN",
              1,
              "Islamic Republic of Iran",
              "Iran",
              "Islamic Republic of Iran",
              "IR",
              "Iranian"),
          new Country(
              "IQ", "IRQ", 1, "Republic of Iraq", "Iraq", "Republic of Iraq", "IQ", "Iraqi"),
          new Country(
              "IE",
              "IRL",
              1,
              "Republic of Ireland",
              "Ireland",
              "Republic of Ireland",
              "IE",
              "Irish"),
          new Country("IM", "IMN", 1, "Isle of Man", "Isle of Man", "Isle of Man", "GB", "Manx"),
          new Country(
              "IL", "ISR", 1, "State of Israel", "Israel", "State of Israel", "IL", "Israeli"),
          new Country(
              "IT", "ITA", 1, "Italian Republic", "Italy", "Italian Republic", "IT", "Italian"),
          new Country("JM", "JAM", 1, "Jamaica", "Jamaica", "Jamaica", "JM", "Jamaican"),
          new Country("JP", "JPN", 1, "Japan", "Japan", "Japan", "JP", "Japanese"),
          new Country(
              "JE",
              "JEY",
              1,
              "Bailiwick of Jersey",
              "Jersey",
              "Bailiwick of Jersey",
              "GB",
              "British"),
          new Country(
              "JO",
              "JOR",
              1,
              "Hashemite Kingdom of Jordan",
              "Jordan",
              "Hashemite Kingdom of Jordan",
              "JO",
              "Jordanian"),
          new Country(
              "KZ",
              "KAZ",
              1,
              "Republic of Kazakhstan",
              "Kazakhstan",
              "Republic of Kazakhstan",
              "KZ",
              "Kazakhstani"),
          new Country(
              "KE", "KEN", 1, "Republic of Kenya", "Kenya", "Republic of Kenya", "KE", "Kenyan"),
          new Country(
              "KI",
              "KIR",
              1,
              "Republic of Kiribati",
              "Kiribati",
              "Republic of Kiribati",
              "KI",
              "I-Kiribati"),
          new Country(
              "KW", "KWT", 1, "State of Kuwait", "Kuwait", "State of Kuwait", "KW", "Kuwaiti"),
          new Country(
              "KG",
              "KGZ",
              1,
              "Kyrgyz Republic",
              "Kyrgyzstan",
              "Kyrgyz Republic",
              "KG",
              "Kyrgyzstani"),
          new Country(
              "LA",
              "LAO",
              1,
              "Lao People's Democratic Republic",
              "Laos",
              "Lao People's Democratic Republic",
              "LA",
              "Laotian"),
          new Country(
              "LV",
              "LVA",
              1,
              "Republic of Latvia",
              "Latvia",
              "Republic of Latvia",
              "LV",
              "Latvian"),
          new Country(
              "LB",
              "LBN",
              1,
              "Lebanese Republic",
              "Lebanon",
              "Lebanese Republic",
              "LB",
              "Lebanese"),
          new Country(
              "LS",
              "LSO",
              1,
              "Kingdom of Lesotho",
              "Lesotho",
              "Kingdom of Lesotho",
              "LS",
              "Mosotho"),
          new Country(
              "LR",
              "LBR",
              1,
              "Republic of Liberia",
              "Liberia",
              "Republic of Liberia",
              "LR",
              "Liberian"),
          new Country("LY", "LBY", 1, "State of Libya", "Libya", "State of Libya", "LY", "Libyan"),
          new Country(
              "LI",
              "LIE",
              1,
              "Principality of Liechtenstein",
              "Liechtenstein",
              "Principality of Liechtenstein",
              "LI",
              "Liechtensteiner"),
          new Country(
              "LT",
              "LTU",
              1,
              "Republic of Lithuania",
              "Lithuania",
              "Republic of Lithuania",
              "LT",
              "Lithunian"),
          new Country(
              "LU",
              "LUX",
              1,
              "Grand Duchy of Luxembourg",
              "Luxembourg",
              "Grand Duchy of Luxembourg",
              "LU",
              "Luxembourger"),
          new Country("MO", "MAC", 1, "Macao", "Macao", "Macao", "CN", "Macanese"),
          new Country(
              "MG",
              "MDG",
              1,
              "Republic of Madagascar",
              "Madagascar",
              "Republic of Madagascar",
              "MG",
              "Malagasy"),
          new Country(
              "MW",
              "MWI",
              1,
              "Republic of Malawi",
              "Malawi",
              "Republic of Malawi",
              "MW",
              "Malawian"),
          new Country("MY", "MYS", 1, "Malaysia", "Malaysia", "Malaysia", "MY", "Malaysian"),
          new Country(
              "MV",
              "MDV",
              1,
              "Republic of Maldives",
              "Maldives",
              "Republic of Maldives",
              "MV",
              "Maldivan"),
          new Country(
              "ML", "MLI", 1, "Republic of Mali", "Mali", "Republic of Mali", "ML", "Malian"),
          new Country(
              "MT", "MLT", 1, "Republic of Malta", "Malta", "Republic of Malta", "MT", "Maltese"),
          new Country(
              "MH",
              "MHL",
              1,
              "Republic of the Marshall Islands",
              "Marshall Islands",
              "Republic of the Marshall Islands",
              "MH",
              "Marshallese"),
          new Country("MQ", "MTQ", 1, "Martinique", "Martinique", "Martinique", "FR", "Martinican"),
          new Country(
              "MR",
              "MRT",
              1,
              "Islamic Republic of Mauritania",
              "Mauritania",
              "Islamic Republic of Mauritania",
              "MR",
              "Mauritanian"),
          new Country(
              "MU",
              "MUS",
              1,
              "Republic of Mauritius",
              "Mauritius",
              "Republic of Mauritius",
              "MU",
              "Mauritian"),
          new Country(
              "YT",
              "MYT",
              1,
              "Department of Mayotte",
              "Mayotte",
              "Department of Mayotte",
              "FR",
              "Mahoran"),
          new Country(
              "MX",
              "MEX",
              1,
              "United Mexican States",
              "Mexico",
              "United Mexican States",
              "MX",
              "Mexican"),
          new Country(
              "FM",
              "FSM",
              1,
              "Federated States of Micronesia",
              "Micronesia",
              "Federated States of Micronesia",
              "FM",
              "Micronesian"),
          new Country(
              "MD",
              "MDA",
              1,
              "Republic of Moldova",
              "Moldova",
              "Republic of Moldova",
              "MD",
              "Moldovan"),
          new Country(
              "MC",
              "MCO",
              1,
              "Principality of Monaco",
              "Monaco",
              " Principality of Monaco",
              "MC",
              "Monacan"),
          new Country("MN", "MNG", 1, "Mongolia", "Mongolia", "Mongolia", "MN", "Mongolian"),
          new Country(
              "ME", "MNE", 1, "Montenegro", "Montenegro", "Montenegro", "ME", "Montenegrin"),
          new Country(
              "MS", "MSR", 1, "Montserrat", "Montserrat", "Montserrat", "GB", "Montserratian"),
          new Country(
              "MA",
              "MAR",
              1,
              "Kingdom of Morocco",
              "Morocco",
              "Kingdom of Morocco",
              "MA",
              "Moroccan"),
          new Country(
              "MZ",
              "MOZ",
              1,
              "Republic of Mozambique",
              "Mozambique",
              "Republic of Mozambique",
              "MZ",
              "Mozambican"),
          new Country(
              "MM",
              "MMR",
              1,
              "Republic of the Union of Myanmar",
              "Myanmar",
              "Republic of the Union of Myanmar",
              "MM",
              "Myanma"),
          new Country(
              "NA",
              "NAM",
              1,
              "Republic of Namibia",
              "Namibia",
              "Republic of Namibia",
              "NA",
              "Namibian"),
          new Country(
              "NR", "NRU", 1, "Republic of Nauru", "Nauru", "Republic of Nauru", "NR", "Nauruan"),
          new Country(
              "NP",
              "NPL",
              1,
              "Federal Democratic Republic of Nepal",
              "Nepal",
              "Federal Democratic Republic of Nepal",
              "NP",
              "Nepalese"),
          new Country("NL", "NLD", 1, "Netherlands", "Netherlands", "Netherlands", "NL", "Dutch"),
          new Country(
              "NC",
              "NCL",
              1,
              "New Caledonia",
              "New Caledonia",
              "New Caledonia",
              "FR",
              "New Caledonian"),
          new Country(
              "NZ", "NZL", 1, "New Zealand", "New Zealand", "New Zealand", "NZ", "New Zealander"),
          new Country(
              "NI",
              "NIC",
              1,
              "Republic of Nicaragua",
              "Nicaragua",
              "Republic of Nicaragua",
              "NI",
              "Nicaraguan"),
          new Country(
              "NE",
              "NER",
              1,
              "Republic of the Niger",
              "Niger",
              "Republic of the Niger",
              "NE",
              "Nigerien"),
          new Country(
              "NG",
              "NGA",
              1,
              "Federal Republic of Nigeria",
              "Nigeria",
              "Federal Republic of Nigeria",
              "NG",
              "Nigerian"),
          new Country("NU", "NIU", 1, "Niue", "Niue", "Niue", "NU", "Niuean"),
          new Country(
              "NF",
              "NFK",
              1,
              "Norfolk Island",
              "Norfolk Island",
              "Norfolk Island",
              "AU",
              "Norfolk Islander"),
          new Country(
              "KP",
              "PRK",
              1,
              "Democratic People's Republic of Korea",
              "North Korea",
              "Democratic People's Republic of Korea",
              "KP",
              "North Korean"),
          new Country(
              "MK",
              "MKD",
              1,
              "Republic of North Macedonia",
              "North Macedonia",
              "Republic of North Macedonia",
              "MK",
              "Macedonian"),
          new Country(
              "MP",
              "MNP",
              1,
              "Commonwealth of the Northern Mariana Islands",
              "Northern Mariana Islands",
              "Commonwealth of the Northern Mariana Islands",
              "US",
              "Northern Mariana Islander"),
          new Country(
              "NO",
              "NOR",
              1,
              "Kingdom of Norway",
              "Norway",
              "Kingdom of Norway",
              "NO",
              "Norwegian"),
          new Country(
              "OM", "OMN", 1, "Sultanate of Oman", "Oman", "Sultanate of Oman", "OM", "Omani"),
          new Country(
              "PR",
              "PRI",
              1,
              "Commonwealth of Puerto Rico",
              "PRT Rico",
              "Commonwealth of Puerto Rico",
              "PR",
              "Puerto Rican"),
          new Country(
              "PK",
              "PAK",
              1,
              "Islamic Republic of Pakistan",
              "Pakistan",
              "Islamic Republic of Pakistan",
              "PK",
              "Pakistani"),
          new Country(
              "PW", "PLW", 1, "Republic of Palau", "Palau", "Republic of Palau", "PW", "Palauan"),
          new Country(
              "PS",
              "PSE",
              1,
              "State of Palestine",
              "Palestine",
              "State of Palestine",
              "PS",
              "Palestinian"),
          new Country(
              "PA",
              "PAN",
              1,
              "Republic of Panama",
              "Panama",
              "Republic of Panama",
              "PA",
              "Panamanian"),
          new Country(
              "PG",
              "PNG",
              1,
              "Independent State of Papua New Guinea",
              "Papua New Guinea",
              "Independent State of Papua New Guinea",
              "PG",
              "Papua New Guinean"),
          new Country(
              "PY",
              "PRY",
              1,
              "Republic of Paraguay",
              "Paraguay",
              "Republic of Paraguay",
              "PY",
              "Paraguayan"),
          new Country(
              "PE", "PER", 1, "Republic of Peru", "Peru", "Republic of Peru", "PE", "Peruvian"),
          new Country(
              "PH",
              "PHL",
              1,
              "Republic of the Philippines",
              "Philippines",
              "Republic of the Philippines",
              "PH",
              "Filipino"),
          new Country(
              "PN",
              "PCN",
              1,
              "Pitcairn Islands",
              "Pitcairn Islands",
              "Pitcairn Islands",
              "GB",
              "Pitcairn Islander"),
          new Country(
              "PL", "POL", 1, "Republic of Poland", "Poland", "Republic of Poland", "PL", "Polish"),
          new Country(
              "PT",
              "PRT",
              1,
              "Portuguese Republic",
              "Portugal",
              "Portuguese Republic",
              "PT",
              "Portuguese"),
          new Country("QA", "QAT", 1, "State of Qatar", "Qatar", "State of Qatar", "QA", "Qatari"),
          new Country(
              "CV",
              "CPV",
              1,
              "Republic of Cabo Verde (Cape Verde)",
              "Republic of Cabo Verde",
              "Republic of Cabo Verde (Cape Verde)",
              "CV",
              "Cape Verdean"),
          new Country("RO", "ROU", 1, "Romania", "Romania", "Romania", "RO", "Romanian"),
          new Country(
              "RU",
              "RUS",
              1,
              "Russian Federation",
              "Russia",
              "Russian Federation",
              "RU",
              "Russian"),
          new Country(
              "RW",
              "RWA",
              1,
              "Republic of Rwanda",
              "Rwanda",
              "Republic of Rwanda",
              "RW",
              "Rwandan"),
          new Country("RE", "REU", 1, "Réunion", "Réunion", "Réunion", "FR", "French"),
          new Country(
              "VC",
              "VCT",
              1,
              "Saint Vincent and the Grenadines",
              "Saint Vincent",
              "Saint Vincent and the Grenadines",
              "VC",
              "Saint Vincentian"),
          new Country(
              "WS",
              "WSM",
              1,
              "Independent State of Samoa",
              "Samoa",
              "Independent State of Samoa",
              "WS",
              "Samoan"),
          new Country(
              "SM",
              "SMR",
              1,
              "Republic of San Marino",
              "San Marino",
              "Republic of San Marino",
              "SM",
              "Sammarinese"),
          new Country(
              "ST",
              "STP",
              1,
              "Democratic Republic of São Tomé and Príncipe",
              "Sao Tome and Principe",
              "Democratic Republic of São Tomé and Príncipe",
              "ST",
              "São Tomean"),
          new Country(
              "SA",
              "SAU",
              1,
              "Kingdom of Saudi Arabia",
              "Saudi Arabia",
              "Kingdom of Saudi Arabia",
              "SA",
              "Saudi Arabian"),
          new Country(
              "SN",
              "SEN",
              1,
              "Republic of Senegal",
              "Senegal",
              "Republic of Senegal",
              "SN",
              "Senegalese"),
          new Country(
              "RS",
              "SRB",
              1,
              "Republic of Serbia",
              "Serbia",
              "Republic of Serbia",
              "RS",
              "Serbian"),
          new Country(
              "SC",
              "SYC",
              1,
              "Republic of Seychelles",
              "Seychelles",
              "Republic of Seychelles",
              "SC",
              "Seychellois"),
          new Country(
              "SL",
              "SLE",
              1,
              "Republic of Sierra Leone",
              "Sierra Leone",
              "Republic of Sierra Leone",
              "SL",
              "Sierra Leonean"),
          new Country(
              "SG",
              "SGP",
              1,
              "Republic of Singapore",
              "Singapore",
              "Republic of Singapore",
              "SG",
              "Singaporean"),
          new Country(
              "SX",
              "SXM",
              1,
              "Sint Maarten (Dutch part)",
              "Sint Maarten",
              "Sint Maarten (Dutch part)",
              "NL",
              "Dutch"),
          new Country(
              "SK", "SVK", 1, "Slovak Republic", "Slovakia", "Slovak Republic", "SK", "Slovak"),
          new Country(
              "SI",
              "SVN",
              1,
              "Republic of Slovenia",
              "Slovenia",
              "Republic of Slovenia",
              "SI",
              "Slovene"),
          new Country(
              "SB",
              "SLB",
              1,
              "Solomon Islands",
              "Solomon Islands",
              "Solomon Islands",
              "SB",
              "Solomon Islander"),
          new Country(
              "SO",
              "SOM",
              1,
              "Federal Republic of Somalia",
              "Somalia",
              "Federal Republic of Somalia",
              "SO",
              "Somali"),
          new Country(
              "ZA",
              "ZAF",
              1,
              "Republic of South Africa",
              "South Africa",
              "Republic of South Africa",
              "ZA",
              "South African"),
          new Country(
              "KR",
              "KOR",
              1,
              "Republic of Korea",
              "South Korea",
              "Republic of Korea",
              "KR",
              "South Korean"),
          new Country(
              "SS",
              "SSD",
              1,
              "Republic of South Sudan",
              "South Sudan",
              "Republic of South Sudan",
              "SS",
              "Sudanese"),
          new Country(
              "ES", "ESP", 1, "Kingdom of Spain", "Spain", "Kingdom of Spain", "ES", "Spanish"),
          new Country(
              "LK",
              "LKA",
              1,
              "Democratic Socialist Republic of Sri Lanka",
              "Sri Lanka",
              "Democratic Socialist Republic of Sri Lanka",
              "LK",
              "Sri Lankan"),
          new Country(
              "BL",
              "BLM",
              1,
              "Saint Barthélemy",
              "St. Barthélemy",
              "Saint Barthélemy",
              "FR",
              "Barthélemois"),
          new Country(
              "KN",
              "KNA",
              1,
              "Federation of Saint Christopher and Nevis",
              "St. Kitts and Nevis",
              "Federation of Saint Christopher and Nevis",
              "KN",
              "Kittian or Nevisian"),
          new Country(
              "LC", "LCA", 1, "Saint Lucia", "St. Lucia", "Saint Lucia", "LC", "Saint Lucian"),
          new Country(
              "MF",
              "MAF",
              1,
              "Saint Martin (French part)",
              "St. Martin (French part)",
              "Saint Martin (French part)",
              "FR",
              "French"),
          new Country(
              "PM",
              "SPM",
              1,
              "Saint Pierre and Miquelon",
              "St. Pierre and Miquelon",
              "Saint Pierre and Miquelon",
              "FR",
              "Miquelonnais"),
          new Country(
              "SD",
              "SDN",
              1,
              "Republic of the Sudan",
              "Sudan",
              "Republic of the Sudan",
              "SD",
              "Sudanese"),
          new Country(
              "SR",
              "SUR",
              1,
              "Republic of Suriname",
              "Suriname",
              "Republic of Suriname",
              "SR",
              "Surinamese"),
          new Country(
              "SJ",
              "SJM",
              1,
              "Svalbard and Jan Mayen",
              "Svalbard and Jan Mayen",
              "Svalbard and Jan Mayen",
              "NO",
              "Norwegian"),
          new Country(
              "SZ",
              "SWZ",
              1,
              "Kingdom of Eswatini",
              "Swaziland",
              "Kingdom of Eswatini",
              "SZ",
              "Swazi"),
          new Country(
              "SE", "SWE", 1, "Kingdom of Sweden", "Sweden", "Kingdom of Sweden", "SE", "Swedish"),
          new Country("CH", "CHE", 1, "Switzerland", "Switzerland", "Switzerland", "CH", "Swiss"),
          new Country(
              "SY",
              "SYR",
              1,
              "Syrian Arab Republic",
              "Syria",
              "Syrian Arab Republic",
              "SY",
              "Syrian"),
          new Country(
              "TW",
              "TWN",
              1,
              "Republic of China",
              "Taiwan",
              "Republic of China",
              "TW",
              "Taiwanese"),
          new Country(
              "TJ",
              "TJK",
              1,
              "Republic of Tajikistan",
              "Tajikistan",
              "Republic of Tajikistan",
              "TJ",
              "Tajikistani"),
          new Country(
              "TZ",
              "TZA",
              1,
              "United Republic of Tanzania",
              "Tanzania",
              "United Republic of Tanzania",
              "TZ",
              "Tanzanian"),
          new Country(
              "TH",
              "THA",
              1,
              "Kingdom of Thailand",
              "Thailand",
              "Kingdom of Thailand",
              "TH",
              "Thai"),
          new Country(
              "BS",
              "BHS",
              1,
              "Commonwealth of The Bahamas",
              "The Bahamas",
              "Commonwealth of The Bahamas",
              "BS",
              "Bahamian"),
          new Country(
              "TG", "TGO", 1, "Togolese Republic", "Togo", "Togolese Republic", "TG", "Togolese"),
          new Country(
              "TK", "TKL", 1, "Tokelau Islands", "Tokelau", "Tokelau Islands", "NZ", "Tokelauan"),
          new Country(
              "TO", "TON", 1, "Kingdom of Tonga", "Tonga", "Kingdom of Tonga", "TO", "Tongan"),
          new Country(
              "TT",
              "TTO",
              1,
              "Republic of Trinidad and Tobago",
              "Trinidad and Tobago",
              "Republic of Trinidad and Tobago",
              "TT",
              "Trinidadian and Tobagonian"),
          new Country(
              "TN",
              "TUN",
              1,
              "Republic of Tunisia",
              "Tunisia",
              "Republic of Tunisia",
              "TN",
              "Tunisian"),
          new Country(
              "TR",
              "TUR",
              1,
              "Republic of Turkey",
              "Turkey",
              "Republic of Turkey",
              "TR",
              "Turkish"),
          new Country(
              "TM", "TKM", 1, "Turkmenistan", "Turkmenistan", "Turkmenistan", "TM", "Turkmen"),
          new Country(
              "TC",
              "TCA",
              1,
              "Turks and Caicos Islands",
              "Turks and Caicos Islands",
              "Turks and Caicos Islands",
              "GB",
              "Turks and Caicos Islander"),
          new Country("TV", "TUV", 1, "Tuvalu", "Tuvalu", "Tuvalu", "TV", "Tuvaluan"),
          new Country(
              "VI",
              "VIR",
              1,
              "United States Virgin Islands",
              "U.S. Virgin Islands",
              "United States Virgin Islands",
              "US",
              "Virgin Islander"),
          new Country(
              "UM",
              "UMI",
              1,
              "United States Minor Outlying Islands",
              "US Minor Outlying Islands",
              "United States Minor Outlying Islands",
              "UM",
              "American"),
          new Country(
              "UG",
              "UGA",
              1,
              "Republic of Uganda",
              "Uganda",
              "Republic of Uganda",
              "UG",
              "Ugandan"),
          new Country("UA", "UKR", 1, "Ukraine", "Ukraine", "Ukraine", "UA", "Ukrainian"),
          new Country(
              "AE",
              "ARE",
              1,
              "United Arab Emirates",
              "United Arab Emirates",
              "United Arab Emirates",
              "AE",
              "Emirati"),
          new Country(
              "GB",
              "GBR",
              1,
              "United Kingdom",
              "United Kingdom",
              "United Kingdom of Great Britain and Northern Ireland",
              "GB",
              "British"),
          new Country(
              "US",
              "USA",
              1,
              "United States of America",
              "United States of America",
              "United States of America",
              "US",
              "American"),
          new Country(
              "UY",
              "URY",
              1,
              "Oriental Republic of Uruguay",
              "Uruguay",
              "Oriental Republic of Uruguay",
              "UY",
              "Uruguayan"),
          new Country(
              "UZ",
              "UZB",
              1,
              "Republic of Uzbekistan",
              "Uzbekistan",
              "Republic of Uzbekistan",
              "UZ",
              "Uzbekistani"),
          new Country(
              "VU",
              "VUT",
              1,
              "Republic of Vanuatu",
              "Vanuatu",
              "Republic of Vanuatu",
              "VU",
              "Ni-Vanuatu"),
          new Country(
              "VE",
              "VEN",
              1,
              "Bolivarian Republic of Venezuela",
              "Venezuela",
              "Bolivarian Republic of Venezuela",
              "VE",
              "Venezuelan"),
          new Country(
              "VN",
              "VNM",
              1,
              "Socialist Republic of Vietnam",
              "Vietnam",
              "Socialist Republic of Vietnam",
              "VN",
              "Vietnamese"),
          new Country(
              "WF",
              "WLF",
              1,
              "Territory of the Wallis and Futuna Islands",
              "Wallis and Futuna Islands",
              "Territory of the Wallis and Futuna Islands",
              "FR",
              "Wallisian or Futunan"),
          new Country(
              "EH",
              "ESH",
              1,
              "Western Sahara",
              "Western Sahara",
              "Western Sahara",
              "EH",
              "Western Saharan"),
          new Country(
              "YE", "YEM", 1, "Republic of Yemen", "Yemen", "Republic of Yemen", "YE", "Yemeni"),
          new Country(
              "ZM",
              "ZMB",
              1,
              "Republic of Zambia",
              "Zambia",
              "Republic of Zambia",
              "ZM",
              "Zambian"),
          new Country(
              "ZW",
              "ZWE",
              1,
              "Republic of Zimbabwe",
              "Zimbabwe",
              "Republic of Zimbabwe",
              "ZW",
              "Zimbabwean"),
          new Country(
              "AX", "ALA", 1, "Åland Islands", "Åland Islands", "Åland Islands", "FI", "Ålandic"));

  /** Private default constructor to enforce singleton pattern. */
  private Countries() {}

  /**
   * Retrieve the country with the specified ISO 3166-1 alpha-2 code.
   *
   * @param code the ISO 3166-1 alpha-2 code for the country
   * @return an Optional containing the country with the specified ISO 3166-1 alpha-2 code or an
   *     empty Optional if the country could not be found
   */
  public static Optional<Country> getByCode(String code) {
    for (Country country : countries) {
      if (country.getCode().equals(code)) {
        return Optional.of(country);
      }
    }

    return Optional.empty();
  }

  /**
   * Retrieve the country with the specified ISO 3166-1 alpha-3 code.
   *
   * @param iso3Code the ISO 3166-1 alpha-3 code for the country
   * @return an Optional containing the country with the specified ISO 3166-1 alpha-3 code or an
   *     empty Optional if the country could not be found
   */
  public static Optional<Country> getByIso3Code(String iso3Code) {
    for (Country country : countries) {
      if (country.getIso3Code().equals(iso3Code)) {
        return Optional.of(country);
      }
    }

    return Optional.empty();
  }

  /**
   * Retrieve the ISO 3166-1 alpha-2 code for the ISO 3166-1 alpha-3 code for the country.
   *
   * @param code the ISO 3166-1 alpha-3 code for the country
   * @return an Optional containing the ISO 3166-1 alpha-2 code for the ISO 3166-1 alpha-3 code for
   *     the country or an empty Optional if the country with the specified ISO 3166-1 alpha-3 code
   *     could not be found
   */
  public static Optional<String> getCodeForIso3Code(String code) {
    return getByIso3Code(code).map(Country::getCode);
  }

  /**
   * Returns the list of countries.
   *
   * @return the list of countries
   */
  public static List<Country> getCountries() {
    return countries;
  }

  /**
   * Retrieve the ISO 3166-1 alpha-3 code for the ISO 3166-1 alpha-2 code for the country.
   *
   * @param code the ISO 3166-1 alpha-2 code for the country
   * @return an Optional containing the ISO 3166-1 alpha-3 code for the ISO 3166-1 alpha-2 code for
   *     the country or an empty Optional if the country with the specified ISO 3166-1 alpha-2 code
   *     could not be found
   */
  public static Optional<String> getIso3CodeForCode(String code) {
    return getByCode(code).map(Country::getIso3Code);
  }
}
